### ISSUE TITLE
Ghost' object has no attribute 'open' 

### ISSUE THREAD

**Issue by DreamFlyHigh** [jeanphix/Ghost.py#189]
RT

**Comment by shekspir55** [comment]
Hi, is there any update?

**Comment by jeanphix** [comment]
@shekspir55 can you paste a failing script?

**Comment by shekspir55** [comment]
from ghost import Ghost
url = "http://www.ebay.com/"
gh = Ghost()
# We load the main page of ebay
page, resources = gh.open(url, wait_onload_event=True)
# Full the main bar and click on the search button
gh.set_field_value("#gh-ac", "plane")
gh.click("#gh-btn")
# Wait for the next page
gh.wait_for_selector("#e1-15")
# Save the image of the screen
gh.capture_to("plane.png")



from here -->http://ghostpy.readthedocs.org/en/latest/#examples

**Comment by jeanphix** [comment]
@shekspir55 This doc is from a fork, ``Ghost.py`` official doc is here: http://ghost-py.readthedocs.org/en/latest/

**Comment by shekspir55** [comment]
Oh, sorry then.
Is there a bit more examples of using it?
Thank you.

**Comment by n-k-d** [comment]
Any working Example for Ghost ? I am also facing the same problem : 

  File "testScript.py", line 6, in <module>
    page, extra_resources = ghost.open("http://microsoft.com")
AttributeError: 'Ghost' object has no attribute 'open'

**Comment by ghost** [comment]
You need to use a ghost session. This works for me:

``` python
import ghost

g = ghost.Ghost()
with g.start() as session:
    page, extra_resources = session.open("https://www.debian.org")
    if page.http_status == 200 and \
            'The Universal Operating System' in page.content:
        print("Good!")
```

**Comment by Lorryrui** [comment]
Thanks for MartinBorg`s example

**Comment by lai32290** [comment]
Thank you @MartinBorg

**Comment by wenhaoliang** [comment]
Thanks for MartinBorg

**Comment by yinzishao** [comment]
Thank you @MartinBorg

**Comment by science641** [comment]
Thank you @MartinBorg this works for me as well but how do you find it and how can we develop it? Is there any tut or manual? Thanks

**Comment by mingyun** [comment]
thanks for @MartinBorg

**Comment by hu0097** [comment]
thanks for @MartinBorg
