### ISSUE TITLE
Python3+PyQt4 QNetworkCookie problem

### ISSUE THREAD

**Issue by sebmos** [jeanphix/Ghost.py#201]
I'm using Ghost.py using Python 3 with PyQt4. It works perfectly, except for one detail:
When a QNetworkCookie is initialized, it converts the str object to a byte array, takes the string representation of that and puts it in a QByteArray object.

```python
>>> from PyQt4 import QtNetwork
>>> c = QtNetwork.QNetworkCookie("cookie_name", "cookie_value")
>>> print(c.toRawForm())
b'cookie_name=cookie_value'
>>> print(repr(c.toRawForm()))
PyQt4.QtCore.QByteArray(b'cookie_name=cookie_value')```
>>> print(c.name())
b'cookie_name'
>>> print(repr(c.name()))
PyQt4.QtCore.QByteArray(b'cookie_name')
```

The same does not happen with PyQt4 on Python 2.7, or with PySide/Python 3.
I hope I'm doing something wrong and there's a way to work around that.
If not, here's a caveat for Python 3 support: Don't use it with PyQt4!

**Comment by EvaSDK** [comment]
It should have been fixed in commit ccaeb2f3813691bcbdeed5cc17df59477a9182d2 but if it's not the case, feel free to re-open.
