### ISSUE TITLE
AttributeError: 'Ghost' object has no attribute 'open'

### ISSUE THREAD

**Issue by brianormous** [jeanphix/Ghost.py#204]
I'm trying to run the ebay example as shown here: http://ghostpy.readthedocs.org/en/latest/#examples and I keep getting: "Attribute Error: 'Ghost' object has no attribute 'open'

any help would be great!

**Comment by thebicycleday** [comment]
I am experiencing the same issue -- do you remember what your solution was for this?

**Comment by brianormous** [comment]
I decided to use phantom.js instead...check it out if you havent. Was
really easy and quick to get up and running. Pretty good turorial here:
https://charlesleifer.com/blog/building-bookmarking-service-python-and-phantomjs/

Hope that helps. If you find out the issue with the  ghost py stuff, id
love to know what it is.

Cheers

**Comment by thebicycleday** [comment]
Thanks for the response! I'll have to give phantom.js a try -- I have been trying all night to get ghost to work, but have not yet been able to find a solution : (

**Comment by brianormous** [comment]
What are you generally trying to build? I dug into related code pretty
deep. Maybe i can send you over a few more things to help you jump start
whatever you  are working  on?

**Comment by thebicycleday** [comment]
I have just been working on a simple webscraper. 

I think I might have resolved my issue with ghost.py. I uninstalled PySide and Ghost.py, and installed PyQT4 and Ghost.py. I am no longer getting 'AttributeError: 'Ghost' object has no attribute 'open''. 

It seems to be working, now.
