### ISSUE TITLE
"pip install Ghost.py --pre" doesn't  work.

### ISSUE THREAD

**Issue by BorisChung** [jeanphix/Ghost.py#218]
This is the error message : 

Collecting Ghost.py
  Using cached Ghost.py-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/_b/35m445rd2jvdj4d1h959t2480000gn/T/pip-build-jc5cy2me/Ghost.py/setup.py", line 9, in <module>
        from ghost import __version__
      File "/private/var/folders/_b/35m445rd2jvdj4d1h959t2480000gn/T/pip-build-jc5cy2me/Ghost.py/ghost/__init__.py", line 2, in <module>
        from .ghost import Ghost, Error, TimeoutError, __version__
      File "/private/var/folders/_b/35m445rd2jvdj4d1h959t2480000gn/T/pip-build-jc5cy2me/Ghost.py/ghost/ghost.py", line 60, in <module>
        QtCore = _import("QtCore")
      File "/private/var/folders/_b/35m445rd2jvdj4d1h959t2480000gn/T/pip-build-jc5cy2me/Ghost.py/ghost/ghost.py", line 54, in _import
        module = __import__(name)
    ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PySide/QtCore.so, 2): Library not loaded: libpyside.cpython-34m.1.2.dylib
      Referenced from: /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PySide/QtCore.so
      Reason: image not found

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/_b/35m445rd2jvdj4d1h959t2480000gn/T/pip-build-jc5cy2me/Ghost.py

I don't understand what happened. 

OS : OS X YOSEMITE 10.10.3
pip version : 
pip 6.1.1 from /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (python 3.4)

**Comment by hrdlnk** [comment]
Same problem here.

**Comment by trashcan** [comment]
That error means that pip can't find the pyside library that ghost.py needs. I found that installing pyside through brew fixed this error for me. 
```
# brew install pyside
# pyside_postinstall.py -install
# pip install ghost.py --pre
```

**Comment by sashkab** [comment]
@trashcan thanks!

**Comment by e9t** [comment]
@trashcan :+1:

**Comment by medmunds** [comment]
I was also able to get it to work with a virtualenv pyside (installed through pip, not brew) by running the postinstall step @trashcan suggested. 

Here's the full set of steps that worked for me:

```sh
brew install qt
mkvirtualenv foo
pip install -U pip  # make sure pip is current
pip install PySide
pyside_postinstall.py -install
pip install Ghost.py
```

[OS X Yosemite; python 2.7.9 via brew]

**Comment by jeanphix** [comment]
@medmunds Added this to the readme, thanks :+1:

**Comment by loooog** [comment]
Hi, I was confused about where to find 'pyside_postinstall.py' and how to execute it?
