### ISSUE TITLE
Download files

### ISSUE THREAD

**Issue by gbailey4** [jeanphix/Ghost.py#233]
Can Ghost.py handle file downloads?

**Comment by gurgeh** [comment]
@gbailey4 
After you .click a link that downloads something, check ghost.http_resources.
It should be list (probably just one element long) of HttpResource with the binary content in .content and HTTP headers in .headers. If you open the file URL directly with .open, then the call will return HttpResource-objects instead.

**Comment by kramer65** [comment]
@gurgeh - Do you maybe have some example code which works? I'm trying to download a file but I can't get it to work.. You would really make my year awesome I get this to work..
