### ISSUE TITLE
Error on official docs.

### ISSUE THREAD

**Issue by zymtom** [jeanphix/Ghost.py#248]
Sorry, this isn't really an issue but this was the best place I could think of to post it.

There is a small error on the main page: https://ghost-py.readthedocs.org/en/latest/

<code>
from ghost import Ghost

ghost = Ghost()

with ghost.start() as session:

    page, extra_resources = session.open("http://jeanphix.me")
    assert page.http_status == 200 and 'jeanphix' in <b>ghost.content</b>
</code>

It's supposed to be page.content

**Comment by jeanphix** [comment]
Fixed by https://github.com/jeanphix/Ghost.py/commit/7fc7c6842b6fbe4481ce4ec4241557e8fdce7766
