### ISSUE TITLE
User-Agent header not being used after being modified

### ISSUE THREAD

**Issue by muddafugga** [jeanphix/Ghost.py#253]
When I do:
g = Ghost()
session = g.start()
print session.user_agent

I get the default user agent of 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/535.2 (KHTML, like Gecko) Chrome/15.0.874.121 Safari/535.2'

When I do:
session.user_agent = 'something else'
print session.user_agent

I get 'something else'

But when I capture the HTTP requests (i.e. - with Wireshark), it shows my HTTP requests as still using 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/535.2 (KHTML, like Gecko) Chrome/15.0.874.121 Safari/535.2' as the User-Agent string.

Why?

On a side note, the documentation on readthedocs.org and http://jeanphix.me/Ghost.py/ and GitHub are out of sync.  It's very confusing.  For example, in the documentation it says to pass the user_agent to Ghost(), but the latest release tosses a TypeError (unexpected keyword argument) when you do that.

**Comment by muddafugga** [comment]
After doing a bit more troubleshooting, I tried the following:

g = Ghost()
session = g.start(user_agent = 'something else')

Then the User-Agent string was correctly being used.  I didn't realize that you can only set those values when starting the session.

**Comment by jeanphix** [comment]
You can set default session arguments this way:

```python
g = Ghost(defaults=dict(user_agent='something else'))
```

**Comment by robd518** [comment]
Right, but I want to change the user_agent after the session has already been started.  For example, if I crawl 5 URLs with one session, I want to crawl one of those URLs with a different user-agent string.

**Comment by jeanphix** [comment]
@muddafugga now you can do:

``` python
session.open(user_agent='Your Custom Agent')
```

**Comment by robd518** [comment]
Thanks, this works perfectly!
