### ISSUE TITLE
evaluate() returns "Unable to load requested page" error

### ISSUE THREAD

**Issue by ghost** [jeanphix/Ghost.py#26]
I was trying to get a workaround for the unreliability I'm experiencing using wait_for_selector, so I thought that maybe executing javascript via evaluate function could work. Suppose I want to open facebook page and go to http://www.facebook.com/mobile/ by clicking a link placed in the footer. I did this:

from ghost import Ghost
ghost = Ghost()
ghost.open("http://www.facebook.com/")
ghost.evaluate("document.getElementById('footerContainer').children[1].children[0].click();", expect_loading=True)
ghost.capture_to('mobile.png', region=None, selector=None)

but I receive the following error:

QFont::setPixelSize: Pixel size <= 0 (0)
ERROR:ghost:Frame: TypeError: 'undefined' is not a function
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    ghost.evaluate("document.getElementById('footerContainer').children[1].children[0].click();", expect_loading=True)
  File "/usr/local/lib/python2.7/dist-packages/ghost/ghost.py", line 115, in wrapper
    return self.wait_for_page_loaded()
  File "/usr/local/lib/python2.7/dist-packages/ghost/ghost.py", line 494, in wait_for_page_loaded
    'Unable to load requested page')
  File "/usr/local/lib/python2.7/dist-packages/ghost/ghost.py", line 556, in _wait_for
    raise Exception(timeout_message)
Exception: Unable to load requested page

I tried increasing the waiting time but to no avail. What is the problem here? I tested "document.getElementById('footerContainer').children[1].children[0].click();" and it works even if returns that TypeError.

Regards

**Comment by cheeseleng** [comment]
But, I use the ghost.click and selector,it still give me the "Unable to load requested page" error, I don't know the reason,this is my code:

```
g = Ghost().start(
    user_agent='ozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36')
g.download_images = True
g.set_viewport_size(1368, 768)
g.show()

p, r = g.open('https://passport.jd.com/new/login.aspx', timeout=10000)
time.sleep(10)

print g.exists("#content > div > div.w > div > div.login-tab.login-tab-l > a")
print g.click("#content > div > div.w > div > div.login-tab.login-tab-l > a", expect_loading=True)

```
