### ISSUE TITLE
ImportError: No module named ghost

### ISSUE THREAD

**Issue by ghost** [jeanphix/Ghost.py#268]
I am using anaconda and ipython. I installed PySide and Ghost.py by using pip successfully. But when I import Ghots or PySide in ipython cell, error is return.

ImportError: No module named Ghost

**Comment by jmwebdev** [comment]
Same here; have other applications running PySide but no luck with Ghost.py

**Comment by Oxydros** [comment]
Hi,

As said in the readme, the module name is ghost and not Ghost.
So you can import the class Ghost like this:

``` python
from ghost import Ghost
```

or the module like this:

``` python
import ghost
```

**Comment by ghost** [comment]
Now the error change to :
ImportError: dlopen(/Users/lcc/news/lib/python2.7/site-packages/PySide/QtCore.so, 2): Library not loaded: libpyside-python2.7.1.2.dylib
  Referenced from: /Users/lcc/news/lib/python2.7/site-packages/PySide/QtCore.so
  Reason: image not found

**Comment by ghost** [comment]
When I try to install it in a virtualenv as the readme said. The similar error occur again:

Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/fs/wdftjx594s72xlrlvgbmb2kh0000gn/T/pip-build-kY73vV/Ghost.py/setup.py", line 9, in <module>
        from ghost import **version**
      File "ghost/**init**.py", line 2, in <module>
        from .ghost import (
      File "ghost/ghost.py", line 17, in <module>
        from .bindings import (
      File "ghost/bindings.py", line 47, in <module>
        QtCore = _import("QtCore")
      File "ghost/bindings.py", line 41, in _import
        module = __import__(name)
    ImportError: dlopen(/Users/lcc/.virtualenvs/virtual/lib/python2.7/site-packages/PySide/QtCore.so, 2): Library not loaded: libpyside-python2.7.1.2.dylib
      Referenced from: /Users/lcc/.virtualenvs/virtual/lib/python2.7/site-packages/PySide/QtCore.so
      Reason: image not found

**Comment by bubuzzz** [comment]
This is actually weird. Look like ipython is looking at the wrong path. I used ipython and it shows the exception; however, when i use python shell only, it works. There is nothing relating to ghost here, just the configuration of ipython is wrong

**Comment by EvaSDK** [comment]
If you want to use ipython with modules installed in your virtualenv, you have to install ipython inside the virtualenv as well. This problem does not occur just with ghost.
