### ISSUE TITLE
pyqt ghost sip 

### ISSUE THREAD

**Issue by zhangbowei** [jeanphix/Ghost.py#284]
Pouring pyqt-4.11.4.yosemite.bottle.1.tar.gz
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getusersitepackages'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getusersitepackages'
==> Caveats
Phonon support is broken.

Python modules have been installed and Homebrew's site-packages is not
in your Python sys.path, so you will not be able to import the modules
this formula installed. If you plan to develop with these modules,
please run:
  mkdir -p
##   echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> homebrew.pth

And In my OS X:
## Using pyqt-4.11.4; sip-4.16.9; python virtualenv,virtualenvwrapper.

So I'm installing it in virtualenv (workon  "some")
## And when I run the test:

from ghost import Ghost
ghost = Ghost()
page, extra_resources = ghost.open("http://xiaorui.cc")
## assert page.http_status==200 and 'xiaorui' in ghost.content

I get:
raise Exception("Ghost.py requires PySide or PyQt4")
## Exception: Ghost.py requires PySide or PyQt4

What should I do?

**Comment by aorzh** [comment]
@zhangbowei , did you has some luck with this?

**Comment by zhangbowei** [comment]
sorry, I hasn't use it for a long time.

**Comment by EvaSDK** [comment]
Hopefully brew recipe now no longer fails installing PyQt4 or PySide. In any case, I ran the following code on my machine (not a mac unfortunately), with no problem:
```python
import logging

from ghost import Ghost

logging.basicConfig(level=logging.DEBUG)
ghost = Ghost()

with ghost.start() as session:
    page, extra_resources = session.open("http://xiaorui.cc", timeout=300)
```

Feel free to re-open if you still encounter this issue.
