### ISSUE TITLE
how do i execute submit function？thanks

### ISSUE THREAD

**Issue by Weststreet** [jeanphix/Ghost.py#288]
id="ctl00_plhMain_lnkSchApp" class="purplelink" href="javascript:__doPostBack('ctl00$plhMain$lnkSchApp','')" style="color:Purple;">submit

how do i execute submit function？this is my code：
session.click('#ctl00_plhMain_lnkSchApp')
session.wait_for_page_loaded(60)
print session.content
it print the same page content before execute submit function
somebody can help？thanks

**Comment by yddchsc** [comment]
Hi,I have also miss the same problem, have you solve it?
Could you tell me how to do ?
Thank you.
