### ISSUE TITLE
wait_for text appear in selector

### ISSUE THREAD

**Issue by arthurtalkgoal** [jeanphix/Ghost.py#297]
Hi,

I need to wait_for the page load content into the selector `#J_SellCounter` (instead of the selector itself appear )

```
<span id="J_SellCounter"></span>
```

will become 

```
<span id="J_SellCounter">21</span>
```

How can I wait the results loaded in the selector?

thanks,

**Comment by EvaSDK** [comment]
You should be able to use the `Session.wait_for_text` function for this.
